version: '3'
services:
  app:
    build: .
    container_name: spring_app_fortumo
    ports:
      - "9090:9090"
    environment:
      - JAVA_OPTS="-Xms128M -Xmx512M -XX:PermSize=128m -XX:MaxPermSize=256m"